### ISSUE TITLE
Artisan migrate does not execute the *.sql command(s)

### ISSUE THREAD

**Issue by mikeerickson** [pmatseykanets/laravel-sql-migrations#1]
I installed the package (using new L56 application).  I correctly created the 3 files as expected.  I then added code to the `*up.sql` file (this was generated by Sequel Pro)

```
CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

The next step was to run artisan migrate

```
$ php artisan migrate

Migration table created successfully.
Nothing to migrate.
```

The `migration` table was indeed created as expected, however, the `users` table was not created (hence the reason for `Nothing to migrate` message)

**Comment by pmatseykanets** [comment]
Can you please post the content of the `database/migrations` directory?

```bash
ls -la database/migrations
```

Thanks.

**Comment by mikeerickson** [comment]
```
drwxr-xr-x  4 merickson  staff  136 Jun 20 14:17 .
drwxr-xr-x  6 merickson  staff  204 Jun 20 13:50 ..
-rw-r--r--  1 merickson  staff  603 Jun 20 14:18 2018_06_20_205406_create_users_table.up.sql
-rw-r--r--  1 merickson  staff   54 Jun 20 14:17 2018_06_20_211651_create_users_table.down.sql
```

**Comment by mikeerickson** [comment]
I am debugging the code, and it seems the `apply` method in the `SqlMigration.php` class is never executed (meaning the `up` method is not executed either)

**Comment by mikeerickson** [comment]
OK, I think I have it figured out...

**Comment by mikeerickson** [comment]
1.  I removed the `create_users_table.up.sql` file think it was superfluous.  But, after reviewing the code, I realize that this file is indeed required as it extends `SqlMigrator` class.

2. Further, after recreating the `*.php` migration, it was then reporting that migration completed succssfully, when in fact it was not creating the tables as expected.

3. After further debugging, I realized that the timestamp on all 3 files (*.php, *.up.sql, *.down.sql) must be the same (in my case, I had the *.php created by a subsequent call to `artisan make:migration ... --sql)

After I updated the filenames to all contain the same exact timestamp, then all worked as expected

**Comment by mikeerickson** [comment]
So, my `database/migrations` listing is now as follows (timestamp MUST be the same for each file).

```
total 24
drwxr-xr-x  5 merickson  staff  170 Jun 20 14:44 .
drwxr-xr-x  6 merickson  staff  204 Jun 20 13:50 ..
-rw-r--r--  1 merickson  staff   54 Jun 20 14:44 2018_06_20_143926_create_users_table.down.sql
-rw-r--r--  1 merickson  staff   88 Jun 20 14:39 2018_06_20_143926_create_users_table.php
-rw-r--r--  1 merickson  staff  603 Jun 20 14:44 2018_06_20_143926_create_users_table.up.sql
```

**Comment by mikeerickson** [comment]
I can understand based on your code why the names need have the same timestamp, I am thinking that at a minimum the documentation could be expanded to include these findings :-)

**Comment by pmatseykanets** [comment]
I'm glad that you figured it out and thanks for the feedback. Good point. I've updated the readme stressing that filenames should match.
