### ISSUE TITLE
Allow Laravel 9

### ISSUE THREAD

**Issue by affektde** [pmatseykanets/laravel-sql-migrations#12]
> PHP 8.0.2 Required
> Laravel now requires PHP 8.0.2 or greater.

Maybe we need to drop support for older Laravel Framework-Versions.
In our fork we just added Laravel 9 to our composer.json, but this package maybe needs a mayor version update for Laravel 9.

**Comment by pmatseykanets** [comment]
Laravel 9 support added in [v1.2.0](https://github.com/pmatseykanets/laravel-sql-migrations/releases/tag/v1.2.0)
