### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by EasterAssociates** [pmatseykanets/laravel-sql-migrations#13]
Will this package be updated to support Laravel 9?

**Comment by LfJohnVo** [comment]
@EasterAssociates I think no :/

**Comment by pmatseykanets** [comment]
It will be, hopefully very soon.

**Comment by pmatseykanets** [comment]
Laravel 9 support added in [v1.2.0](https://github.com/pmatseykanets/laravel-sql-migrations/releases/tag/v1.2.0)
